@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/current-user
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "akash",
  "password": "123456",
  "email": "akash@gmail.com",
  "avatarColor": "green",
  "avatarImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "avro",
  "password": "123456"
}

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "avro@gmail.com"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/baf363ff4e1ce5d7ad30edb142fd43fd2192b576
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "123456",
  "confirmPassword": "123456"
}