@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/current-user
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "avro",
  "password": "123456",
  "email": "avro@gmail.com",
  "avatarColor": "green",
  "avatarImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "avro",
  "password": "123456"
}

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": ""
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/<token>
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "",
  "confirmPassword": ""
}