@baseUrl = http://localhost:5000
@urlPath = api/v1


###
POST {{baseUrl}}/{{urlPath}}/reaction/add
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "64730b54e9aeff94d177eb5a",
  "postId": "64734eed05c91dc3ec97649f",
  "type": "wow",
  "profilePicture": "https://res.cloudinary.com/dw5lxxdko/image/upload/v1685010955/SA2Social/646f3a097498984b2c9e4209/profile-picture/646f3a097498984b2c9e420a-profile-pic.jpg",
  "previousReaction": "",
  "postReactions": {"like":0,"love": 0,"happy":0,"wow":1,"sad":0,"angry":0}
}

###
DELETE {{baseUrl}}/{{urlPath}}/reaction/remove
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "postId": "64730f7416f8fc4199e4bf73",
  "previousReaction": "love",
  "postReactions": {"like":0,"love": 0,"happy":0,"wow":0,"sad":0,"angry":0}
}


###
GET {{baseUrl}}/{{urlPath}}/reaction/64734eed05c91dc3ec97649f
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/reaction/64734eed05c91dc3ec97649f/avro
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/reactions/avro
Content-Type: application/json
Accept: application/json
withCredentials: true

