@baseUrl = http://localhost:5000
@urlPath = api/v1

# GET {{baseUrl}}/{{urlPath}}/post/comments/<postId>
###
GET {{baseUrl}}/{{urlPath}}/post/comments/64730f7416f8fc4199e4bf73
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/comments-name/64730f7416f8fc4199e4bf73
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/comments-single/64730f7416f8fc4199e4bf73/647e2fcd34ece6056ab526f3
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comments
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "6497e1d936168e9aeb833b3f",
  "postId": "649b5177a71289b5a4550de6",
  "comment": "comment with notifications 3",
  "profilePicture": "https://res.cloudinary.com/dw5lxxdko/image/upload/v1685261095/SA2Social/64730b26e9aeff94d177eb53/profile-picture/64730b26e9aeff94d177eb53-profile-pic.jpg"
}